fileVersion: 1
id: "30"
mappingDefinitions:
  FOO:
    database: BEN_EDW
    schema: ""
  SAMPLE:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
  WORK:
    database: BEN_EDW
    schema: CANARY_ENV_MAIN
name: Canary Main Environment
type: Environment
