fileVersion: 1
id: "30"
mappingDefinitions:
  DESTINATION:
    database: BEN_EDW
    schema: CANARY_WORKSPACE_MAIN
  SOURCE:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
name: New Environment
type: Environment
