fileVersion: 1
id: "30"
mappingDefinitions:
  SAMPLE:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
  WORK:
    database: BEN_EDW
    schema: CANARY_ENV_MANAGED
name: New Environment
type: Environment
